### ISSUE TITLE
Multiple parallel environments now possible with latest JSBSim version

### ISSUE THREAD

**Issue by opt12** [Gor-Ren/gym-jsbsim#5]
Just for anybody who is interested: The restriction, that it is not possible to have multiple instances of the environment is now gone with the latest rolling release of JSBSim.

Thanks to @bcoconni the underlying bug in JSBSim was fixed last Sunday with https://github.com/JSBSim-Team/jsbsim/commit/2661d7c80607aa2e86676b96a24eaf7dad87c1a9

As this resolves https://github.com/JSBSim-Team/jsbsim/issues/201 it is now possible to instantiate multiple environments which is very common in several ML algos.

**Comment by Gor-Ren** [comment]
Thanks for the heads up! I've updated the README.
