### ISSUE TITLE
failed to gym.make()

### ISSUE THREAD

**Issue by theorynice** [Gor-Ren/gym-jsbsim#6]
Thanks for your great work. I install the gym-jsbsim through _pip install git+https://github.com/Gor-Ren/gym-jsbsim_
when I test by
 `env = gym.make('JSBSim-TurnHeadingControl-Cessna172P-SHAPING.STANDARD-NoFG-v0')

env.reset()
state, reward, done, info = env.step(action)`
The error show: gym.error._UnregisteredEnv: No registered env with id: JSBSim-TurnHeadingControl-Cessna172P-SHAPING.STANDARD-NoFG-v0_
How can I solve the problem?

**Comment by Gor-Ren** [comment]
Probably a problem with the environment id string.

Try,
```
from gym import envs
print(envs.registry.all())
```
Find the env ID you want, and copy it exactly.

**Comment by theorynice** [comment]
@Gor-Ren 
Thanks for your help, but I haven't found the env related to jsbsim in my gym. When I directly import the source code, the issue is same.

**Comment by theorynice** [comment]
@Gor-Ren　Thank you very much, I have run successfully. The solution is mentioned above. I should correct the id string with _"JSBSim-HeadingControl**Task**-Cessna172P-Shaping.STANDARD-NoFG-v0"_. Can I ask how much the reward when training ends?

**Comment by Gor-Ren** [comment]
@theorynice sorry, I don't recall. You can examine the code, or it may be documented in my dissertation. Glad it's working.
