### ISSUE TITLE
Unable to visualize in FlightGear

### ISSUE THREAD

**Issue by lasri049** [Gor-Ren/gym-jsbsim#7]
Hi, I am trying to visualize the training in flightgear and have given env.render(mode='flightgear' ). It throws an error saying 
 ```
 Message=[WinError 2] The system cannot find the file specified
  Source=E:\Kartal-main\gym_jsbsim\visualiser.py
  StackTrace:
  File "E:\Kartal-main\gym_jsbsim\visualiser.py", line 270, in _launch_flightgear
    flightgear_process = subprocess.Popen(
  File "E:\Kartal-main\gym_jsbsim\visualiser.py", line 254, in __init__
    self.flightgear_process = self._launch_flightgear(sim.get_aircraft())
  File "E:\Kartal-main\gym_jsbsim\environment.py", line 128, in render (Current frame)
    self.flightgear_visualiser = FlightGearVisualiser(self.sim,
  File "E:\Kartal-main\try2.py", line 36, in <module>
    env.render(mode='flightgear')
```
FlightGear is installed and I am able to open it from the command window. 

Also I am unable to use any algorithm other than PPO for training. Can you please help me out?

**Comment by lasri049** [comment]
I found that there were some folders that were not yet loaded in FlightGear which I came to know through the 'fgfs --version' command on cmd prompt. A window popped up asking to load some some folders and once that was done, I was able to visualize in FlightGear

**Comment by Li-yg** [comment]
Hello, I met the same problem with you. And I have run  'fgfs --version' ,but it doesn't work. Is there any other thing need to be concerned?
Thanks for your help!
